### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by armanemadi** [dreamingechoes/bootstrap_sb_admin_base_v2#1]
Hi , Great job.

here is a rtl version of template , 
http://startbootstrap.com/template-overviews/sb-admin-2/

is this include your gem file ?

**Comment by dreamingechoes** [comment]
Hi!

right now is not included, but this next week I'll dedicate some time to add it and release a new version with RTL.

Thank you for the suggestion! :)

**Comment by armanemadi** [comment]
Hi again 
Thanks a lot .

__

**Comment by dreamingechoes** [comment]
Hi!

I've just released a new version (0.2.1) of the gem adding the RTL version of the theme. I was about to include the assets of the already existing RTL version of this theme, but I've found that has some occasional bugs, so I decided to create my own RTL version to ensure that everything works properly and I finally added the styles of this one: https://github.com/dreamingechoes/sb-admin2-rtl

Follow the instructions of the README to use this RTL version instead of the regular one (basically it's only include `*= require bootstrap_sb_admin_base_v2_rtl` on your `application.css` instead of the `*= require bootstrap_sb_admin_base_v2`.

Thank you!
