### ISSUE TITLE
Dropdown not work

### ISSUE THREAD

**Issue by lemonnm** [dreamingechoes/bootstrap_sb_admin_base_v2#4]
hi,

When I use the gem the dropdown in navbar not work...
And I have a error with multi level Dropdown maybe a issue but I can't try : 
[http://stackoverflow.com/questions/25875100/sb-admin-2-menu-doesnt-collapse-when-i-edit-some-content](url)

Thx,

**Comment by dreamingechoes** [comment]
Hi lemonnm!

I'll check this bug, and when I have a new version of the gem without this behavior I'll publish and I'll let you know.

Thank you for your feedback, I really appreciate it!

Greetings!

**Comment by dreamingechoes** [comment]
Hi lemonnm!

I've made some changes on the javascript file that sets active or not the elements of the navbar menu, and it seems that now works fine. I've released version 0.2.2 of the gem, can you update to this version and see if now it works properly for you?

I've developed a simple Rails application in order to test the gem and it works fine for me, you can check this app here: https://sensor-admin-panel-testing.herokuapp.com (test email: example@email.com, password: 123456example), and here you have the Github repo to be able to check the code: https://github.com/dreamingechoes/sensors_admin_panel.

Thanks for your feedback!

**Comment by lemonnm** [comment]
Hi dreamingechoes,

Thx for your good gem :) 

It's ok for me!! 
Plz add  in the REDAME : https://github.com/dreamingechoes/sensors_admin_panel 
Read the Gemfile and other file helped me!

Thx you,
